local addonName, DF = ...

-- ============================================================
-- EXPORT/IMPORT CATEGORY DEFINITIONS
-- ============================================================
-- Each setting from PartyDefaults/RaidDefaults is assigned to a category
-- for selective import/export

DF.ExportCategories = {
    -- Frame positions on screen
    position = {
        "anchorPoint",
        "anchorX",
        "anchorY",
        "hideDragOverlay",
        "permanentMover",
        "permanentMoverActionLeft",
        "permanentMoverActionRight",
        "permanentMoverActionShiftLeft",
        "permanentMoverActionShiftRight",
        "permanentMoverAnchor",
        "permanentMoverAttachTo",
        "permanentMoverColor",
        "permanentMoverCombatColor",
        "permanentMoverHeight",
        "permanentMoverHideInCombat",
        "permanentMoverOffsetX",
        "permanentMoverOffsetY",
        "permanentMoverPullTimerDuration",
        "permanentMoverShowOnHover",
        "permanentMoverWidth",
        "raidAnchorX",
        "raidAnchorY",
        "raidEnabled",
        "raidLocked",
    },
    -- Size, spacing, growth, sorting
    layout = {
        "frameHeight",
        "framePadding",
        "frameScale",
        "frameSpacing",
        "frameWidth",
        "gridSize",
        "growDirection",
        "growthAnchor",
        "hideDefaultPlayerFrame",
        "hidePlayerFrame",
        "locked",
        "pixelPerfect",
        "raidFlatColumnAnchor",
        "raidFlatFrameAnchor",
        "raidFlatGrowthAnchor",
        "raidFlatHorizontalSpacing",
        "raidFlatPlayerAnchor",
        "raidFlatReverseFillOrder",
        "raidFlatVerticalSpacing",
        "raidGroupAnchor",
        "raidGroupDisplayOrder",
        "raidGroupOrder",
        "raidGroupRowGrowth",
        "raidGroupSpacing",
        "raidGroupVisible",
        "raidGroupsPerRow",
        "raidPlayerAnchor",
        "raidPlayerGroupFirst",
        "raidPlayersPerRow",
        "raidRowColSpacing",
        "raidTestFrameCount",
        "raidUseGroups",
        "restedIndicator",
        "restedIndicatorAnchor",
        "restedIndicatorGlow",
        "restedIndicatorIcon",
        "restedIndicatorOffsetX",
        "restedIndicatorOffsetY",
        "restedIndicatorSize",
        "snapToGrid",
        "soloMode",
        "sortAlphabetical",
        "sortByClass",
        "sortClassOrder",
        "sortEnabled",
        "sortRoleOrder",
        "sortSelfPosition",
        "sortSeparateMeleeRanged",
        "testFrameCount",
        "useFrameSort",
    },
    -- Health, power, absorb and heal-prediction bars
    bars = {
        "absorbBarAnchor",
        "absorbBarAttachedClampMode",
        "absorbBarBackgroundColor",
        "absorbBarBlendMode",
        "absorbBarBorderColor",
        "absorbBarBorderEnabled",
        "absorbBarBorderSize",
        "absorbBarColor",
        "absorbBarFrameLevel",
        "absorbBarHeight",
        "absorbBarMode",
        "absorbBarOrientation",
        "absorbBarOverlayReverse",
        "absorbBarOvershieldAlpha",
        "absorbBarOvershieldColor",
        "absorbBarOvershieldReverse",
        "absorbBarOvershieldStyle",
        "absorbBarReverse",
        "absorbBarShowOvershield",
        "absorbBarStrata",
        "absorbBarTexture",
        "absorbBarWidth",
        "absorbBarX",
        "absorbBarY",
        "backgroundClassAlpha",
        "backgroundColor",
        "backgroundColorMode",
        "backgroundMode",
        "backgroundTexture",
        "classColorAlpha",
        "classPowerAnchor",
        "classPowerBgColor",
        "classPowerColor",
        "classPowerEnabled",
        "classPowerGap",
        "classPowerHeight",
        "classPowerIgnoreFade",
        "classPowerShowDamager",
        "classPowerShowHealer",
        "classPowerShowTank",
        "classPowerUseCustomColor",
        "classPowerX",
        "classPowerY",
        "frameBorderSize",
        "healAbsorbBarAnchor",
        "healAbsorbBarAttachedClampMode",
        "healAbsorbBarBackgroundColor",
        "healAbsorbBarBlendMode",
        "healAbsorbBarBorderColor",
        "healAbsorbBarBorderEnabled",
        "healAbsorbBarBorderSize",
        "healAbsorbBarColor",
        "healAbsorbBarHeight",
        "healAbsorbBarMode",
        "healAbsorbBarOrientation",
        "healAbsorbBarOverlayReverse",
        "healAbsorbBarOvershieldAlpha",
        "healAbsorbBarOvershieldColor",
        "healAbsorbBarOvershieldReverse",
        "healAbsorbBarOvershieldStyle",
        "healAbsorbBarReverse",
        "healAbsorbBarShowOvershield",
        "healAbsorbBarTexture",
        "healAbsorbBarWidth",
        "healAbsorbBarX",
        "healAbsorbBarY",
        "healPredictionAllColor",
        "healPredictionAnchor",
        "healPredictionBackgroundColor",
        "healPredictionBlendMode",
        "healPredictionClampMode",
        "healPredictionEnabled",
        "healPredictionFrameLevel",
        "healPredictionHeight",
        "healPredictionMode",
        "healPredictionMyColor",
        "healPredictionOrientation",
        "healPredictionOthersColor",
        "healPredictionOverflowPercent",
        "healPredictionOverlayReverse",
        "healPredictionReverse",
        "healPredictionShowMode",
        "healPredictionShowOverheal",
        "healPredictionStrata",
        "healPredictionTexture",
        "healPredictionWidth",
        "healPredictionX",
        "healPredictionY",
        "healthColor",
        "healthColorHigh",
        "healthColorHighUseClass",
        "healthColorHighWeight",
        "healthColorLow",
        "healthColorLowUseClass",
        "healthColorLowWeight",
        "healthColorMedium",
        "healthColorMediumUseClass",
        "healthColorMediumWeight",
        "healthColorMode",
        "healthOrientation",
        "healthTexture",
        "missingHealthClassAlpha",
        "missingHealthColor",
        "missingHealthColorHigh",
        "missingHealthColorHighUseClass",
        "missingHealthColorHighWeight",
        "missingHealthColorLow",
        "missingHealthColorLowUseClass",
        "missingHealthColorLowWeight",
        "missingHealthColorMedium",
        "missingHealthColorMediumUseClass",
        "missingHealthColorMediumWeight",
        "missingHealthColorMode",
        "missingHealthGradientAlpha",
        "missingHealthTexture",
        "powerBarHeight",
        "reducedMaxHealthBlendMode",
        "reducedMaxHealthClipHealthBar",
        "reducedMaxHealthColor",
        "reducedMaxHealthEnabled",
        "reducedMaxHealthTexture",
        "resourceBarAnchor",
        "resourceBarBackgroundColor",
        "resourceBarBackgroundEnabled",
        "resourceBarBorderBlendMode",
        "resourceBarBorderColor",
        "resourceBarBorderColorSource",
        "resourceBarBorderEnabled",
        "resourceBarBorderGradientDirection",
        "resourceBarBorderGradientEndColor",
        "resourceBarBorderGradientStartColor",
        "resourceBarBorderInset",
        "resourceBarBorderShadowColor",
        "resourceBarBorderShadowEnabled",
        "resourceBarBorderShadowOffsetX",
        "resourceBarBorderShadowOffsetY",
        "resourceBarBorderShadowSize",
        "resourceBarBorderSize",
        "resourceBarBorderStyle",
        "resourceBarBorderTexture",
        "resourceBarClassColor",
        "resourceBarClassFilter",
        "resourceBarColorMode",
        "resourceBarCustomColor",
        "resourceBarEnabled",
        "resourceBarFrameLevel",
        "resourceBarHeight",
        "resourceBarMatchWidth",
        "resourceBarOrientation",
        "resourceBarReverseFill",
        "resourceBarShowBorder",
        "resourceBarShowDPS",
        "resourceBarShowHealer",
        "resourceBarShowInSoloMode",
        "resourceBarShowTank",
        "resourceBarSmooth",
        "resourceBarTexture",
        "resourceBarWidth",
        "resourceBarX",
        "resourceBarY",
        "showAbsorbBar",
        "showPowerBar",
        "smoothBars",
    },
    -- Buff/debuff icons, filters (blacklist travels with this category)
    auras = {
        "buffAlpha",
        "buffAnchor",
        "buffBorderAnimationColor",
        "buffBorderAnimationCornerLength",
        "buffBorderAnimationFrequency",
        "buffBorderAnimationInset",
        "buffBorderAnimationLength",
        "buffBorderAnimationMask",
        "buffBorderAnimationOffsetX",
        "buffBorderAnimationOffsetY",
        "buffBorderAnimationParticles",
        "buffBorderAnimationScale",
        "buffBorderAnimationSidesAxis",
        "buffBorderAnimationThickness",
        "buffBorderAnimationType",
        "buffBorderBlendMode",
        "buffBorderColor",
        "buffBorderGradientDirection",
        "buffBorderGradientEndColor",
        "buffBorderGradientStartColor",
        "buffBorderInset",
        "buffBorderOffsetX",
        "buffBorderOffsetY",
        "buffBorderShadowColor",
        "buffBorderShadowEnabled",
        "buffBorderShadowOffsetX",
        "buffBorderShadowOffsetY",
        "buffBorderShadowSize",
        "buffBorderSize",
        "buffBorderStyle",
        "buffBorderTexture",
        "buffClickThrough",
        "buffClickThroughInCombatOnly",
        "buffClickThroughKeybinds",
        "buffCountdownFont",
        "buffCountdownOutline",
        "buffCountdownScale",
        "buffCountdownX",
        "buffCountdownY",
        "buffDeduplicateDefensives",
        "buffDisableMouse",
        "buffDurationAnchor",
        "buffDurationColor",
        "buffDurationColorByTime",
        "buffDurationFont",
        "buffDurationFormat",
        "buffDurationHideAboveEnabled",
        "buffDurationHideAboveThreshold",
        "buffDurationOutline",
        "buffDurationScale",
        "buffDurationX",
        "buffDurationY",
        "buffMaxDurationEnabled",
        "buffMaxDurationMinutes",
        "buffExpiringBorderAnimationColor",
        "buffExpiringBorderAnimationCornerLength",
        "buffExpiringBorderAnimationFrequency",
        "buffExpiringBorderAnimationInset",
        "buffExpiringBorderAnimationLength",
        "buffExpiringBorderAnimationMask",
        "buffExpiringBorderAnimationOffsetX",
        "buffExpiringBorderAnimationOffsetY",
        "buffExpiringBorderAnimationParticles",
        "buffExpiringBorderAnimationScale",
        "buffExpiringBorderAnimationSidesAxis",
        "buffExpiringBorderAnimationThickness",
        "buffExpiringBorderAnimationType",
        "buffExpiringBorderColor",
        "buffExpiringBorderColorByTime",
        "buffExpiringBorderEnabled",
        "buffExpiringBorderInset",
        "buffExpiringBorderPulsate",
        "buffExpiringBorderThickness",
        "buffExpiringEnabled",
        "buffExpiringThreshold",
        "buffExpiringThresholdMode",
        "buffExpiringTintColor",
        "buffExpiringTintEnabled",
        "buffFilterCancelable",
        "buffFilterMode",
        "buffFilterPlayer",
        "buffFilterRaid",
        "buffFilterSelection",
        "buffGrowth",
        "buffHideSwipe",
        "buffMax",
        "buffOffsetX",
        "buffOffsetY",
        "buffPaddingX",
        "buffPaddingY",
        "buffScale",
        "buffShowBorder",
        "buffShowCountdown",
        "buffShowDuration",
        "buffSize",
        "buffStackAnchor",
        "buffStackColor",
        "buffStackFont",
        "buffStackMinimum",
        "buffStackOutline",
        "buffStackScale",
        "buffStackX",
        "buffStackY",
        "buffWrap",
        "buffWrapOffsetX",
        "buffWrapOffsetY",
        "debuffAlpha",
        "debuffAnchor",
        "debuffBorderAnimationColor",
        "debuffBorderAnimationCornerLength",
        "debuffBorderAnimationFrequency",
        "debuffBorderAnimationInset",
        "debuffBorderAnimationLength",
        "debuffBorderAnimationMask",
        "debuffBorderAnimationOffsetX",
        "debuffBorderAnimationOffsetY",
        "debuffBorderAnimationParticles",
        "debuffBorderAnimationScale",
        "debuffBorderAnimationSidesAxis",
        "debuffBorderAnimationThickness",
        "debuffBorderAnimationType",
        "debuffBorderBlendMode",
        "debuffBorderColor",
        "debuffBorderColorBleed",
        "debuffBorderColorByType",
        "debuffBorderColorCurse",
        "debuffBorderColorDisease",
        "debuffBorderColorMagic",
        "debuffBorderColorNone",
        "debuffBorderColorPoison",
        "debuffBorderGradientDirection",
        "debuffBorderGradientEndColor",
        "debuffBorderGradientStartColor",
        "debuffBorderInset",
        "debuffBorderOffsetX",
        "debuffBorderOffsetY",
        "debuffBorderShadowColor",
        "debuffBorderShadowEnabled",
        "debuffBorderShadowOffsetX",
        "debuffBorderShadowOffsetY",
        "debuffBorderShadowSize",
        "debuffBorderSize",
        "debuffBorderStyle",
        "debuffBorderTexture",
        "debuffClickThrough",
        "debuffClickThroughInCombatOnly",
        "debuffClickThroughKeybinds",
        "debuffCountdownFont",
        "debuffCountdownOutline",
        "debuffCountdownScale",
        "debuffCountdownX",
        "debuffCountdownY",
        "debuffDisableMouse",
        "debuffDurationAnchor",
        "debuffDurationColorByTime",
        "debuffDurationFont",
        "debuffDispelBorderInset",
        "debuffDurationFormat",
        "debuffDurationColor",
        "debuffStackColor",
        "debuffDurationHideAboveEnabled",
        "debuffDurationHideAboveThreshold",
        "debuffDurationOutline",
        "debuffDurationScale",
        "debuffDurationX",
        "debuffDurationY",
        "debuffExpiringBorderColor",
        "debuffExpiringBorderColorByTime",
        "debuffExpiringBorderEnabled",
        "debuffExpiringBorderInset",
        "debuffExpiringBorderPulsate",
        "debuffExpiringBorderThickness",
        "debuffExpiringEnabled",
        "debuffExpiringThreshold",
        "debuffExpiringThresholdMode",
        "debuffExpiringTintColor",
        "debuffExpiringTintEnabled",
        "debuffFilterBoss",
        "debuffFilterCrowdControl",
        "debuffFilterDispellable",
        "debuffFilterPriority",
        "debuffFilterRaid",
        "debuffFilterRole",
        "debuffGrowth",
        "debuffHideSwipe",
        "debuffMax",
        "debuffMaxDurationEnabled",
        "debuffMaxDurationKeepImportant",
        "debuffMaxDurationMinutes",
        "debuffOffsetX",
        "debuffOffsetY",
        "debuffPaddingX",
        "debuffPaddingY",
        "debuffScale",
        "debuffShowAll",
        "debuffShowBorder",
        "debuffShowCountdown",
        "debuffShowDuration",
        "debuffSize",
        "debuffStackAnchor",
        "debuffStackFont",
        "debuffStackMinimum",
        "debuffStackOutline",
        "debuffStackScale",
        "debuffStackX",
        "debuffStackY",
        "debuffWrap",
        "debuffWrapOffsetX",
        "debuffWrapOffsetY",
        "defensiveFilterSelection",
        "directBuffOnlyMine",
        "directBuffShowAll",
        "directBuffSortOrder",
        "directDebuffDispellableMode",
        "directDebuffShowAll",
        "directDebuffSortOrder",
        "fadeDeadAuras",
        "showBuffs",
        "showDebuffs",
    },
    -- Dispel overlay
    dispel = {
        "dispelAnimate",
        "dispelAnimateSpeed",
        "dispelBorderAlpha",
        "dispelBorderInset",
        "dispelBorderSize",
        "dispelBorderStyle",
        "dispelFrameLevel",
        "dispelGradientAlpha",
        "dispelGradientBlendMode",
        "dispelGradientDarkenAlpha",
        "dispelGradientDarkenEnabled",
        "dispelGradientOnCurrentHealth",
        "dispelGradientSize",
        "dispelGradientStyle",
        "dispelIconAlpha",
        "dispelIconOffsetX",
        "dispelIconOffsetY",
        "dispelIconPosition",
        "dispelIconSize",
        "dispelNameText",
        "dispelOverlayDispelType",
        "dispelOverlayEnabled",
        "dispelShowBorder",
        "dispelShowGradient",
        "dispelShowIcon",
    },
    -- Missing raid-buff indicator
    missingBuffs = {
        "missingBuffCheckAttackPower",
        "missingBuffCheckBronze",
        "missingBuffCheckIntellect",
        "missingBuffCheckSkyfury",
        "missingBuffCheckStamina",
        "missingBuffCheckVersatility",
        "missingBuffClassDetection",
        "missingBuffHideFromBar",
        "missingBuffIconAnchor",
        "missingBuffIconBorderAnimationColor",
        "missingBuffIconBorderAnimationCornerLength",
        "missingBuffIconBorderAnimationFrequency",
        "missingBuffIconBorderAnimationInset",
        "missingBuffIconBorderAnimationLength",
        "missingBuffIconBorderAnimationMask",
        "missingBuffIconBorderAnimationOffsetX",
        "missingBuffIconBorderAnimationOffsetY",
        "missingBuffIconBorderAnimationParticles",
        "missingBuffIconBorderAnimationScale",
        "missingBuffIconBorderAnimationSidesAxis",
        "missingBuffIconBorderAnimationThickness",
        "missingBuffIconBorderAnimationType",
        "missingBuffIconBorderBlendMode",
        "missingBuffIconBorderColor",
        "missingBuffIconBorderColorSource",
        "missingBuffIconBorderGradientDirection",
        "missingBuffIconBorderGradientEndColor",
        "missingBuffIconBorderGradientStartColor",
        "missingBuffIconBorderInset",
        "missingBuffIconBorderOffsetX",
        "missingBuffIconBorderOffsetY",
        "missingBuffIconBorderShadowColor",
        "missingBuffIconBorderShadowEnabled",
        "missingBuffIconBorderShadowOffsetX",
        "missingBuffIconBorderShadowOffsetY",
        "missingBuffIconBorderShadowSize",
        "missingBuffIconBorderSize",
        "missingBuffIconBorderStyle",
        "missingBuffIconBorderTexture",
        "missingBuffIconDebug",
        "missingBuffIconEnabled",
        "missingBuffIconFrameLevel",
        "missingBuffIconScale",
        "missingBuffIconShowBorder",
        "missingBuffIconSize",
        "missingBuffIconX",
        "missingBuffIconY",
    },
    -- Defensive bar + external defensive icon
    defensives = {
        "defensiveBarAnchor",
        "defensiveBarBorderColor",
        "defensiveBarBorderSize",
        "defensiveBarEnabled",
        "defensiveBarFrameLevel",
        "defensiveBarGrowth",
        "defensiveBarIconSize",
        "defensiveBarMax",
        "defensiveBarScale",
        "defensiveBarShowDuration",
        "defensiveBarSpacing",
        "defensiveBarWrap",
        "defensiveBarX",
        "defensiveBarY",
        "defensiveIconAnchor",
        "defensiveIconBorderAnimationColor",
        "defensiveIconBorderAnimationCornerLength",
        "defensiveIconBorderAnimationFrequency",
        "defensiveIconBorderAnimationInset",
        "defensiveIconBorderAnimationLength",
        "defensiveIconBorderAnimationMask",
        "defensiveIconBorderAnimationOffsetX",
        "defensiveIconBorderAnimationOffsetY",
        "defensiveIconBorderAnimationParticles",
        "defensiveIconBorderAnimationScale",
        "defensiveIconBorderAnimationSidesAxis",
        "defensiveIconBorderAnimationThickness",
        "defensiveIconBorderAnimationType",
        "defensiveIconBorderBlendMode",
        "defensiveIconBorderColor",
        "defensiveIconBorderColorSource",
        "defensiveIconBorderGradientDirection",
        "defensiveIconBorderGradientEnabled",
        "defensiveIconBorderGradientEndColor",
        "defensiveIconBorderGradientStartColor",
        "defensiveIconBorderInset",
        "defensiveIconBorderOffsetX",
        "defensiveIconBorderOffsetY",
        "defensiveIconBorderShadowColor",
        "defensiveIconBorderShadowEnabled",
        "defensiveIconBorderShadowOffsetX",
        "defensiveIconBorderShadowOffsetY",
        "defensiveIconBorderShadowSize",
        "defensiveIconBorderSize",
        "defensiveIconBorderStyle",
        "defensiveIconBorderTexture",
        "defensiveIconClickThrough",
        "defensiveIconClickThroughInCombatOnly",
        "defensiveIconClickThroughKeybinds",
        "defensiveIconDisableMouse",
        "defensiveIconDurationColor",
        "defensiveIconDurationColorByTime",
        "defensiveIconDurationFont",
        "defensiveIconDurationOutline",
        "defensiveIconDurationAnchor",
        "defensiveIconDurationScale",
        "defensiveIconDurationX",
        "defensiveIconDurationY",
        "defensiveIconEnabled",
        "defensiveIconFrameLevel",
        "defensiveIconHideSwipe",
        "defensiveIconScale",
        "defensiveIconShowBorder",
        "defensiveIconShowDuration",
        "defensiveIconSize",
        "defensiveIconX",
        "defensiveIconY",
    },
    -- Targeted spells (incl. personal)
    targetedSpells = {
        "personalTargetedSpellAlpha",
        "personalTargetedSpellBorderAnimationColor",
        "personalTargetedSpellBorderAnimationCornerLength",
        "personalTargetedSpellBorderAnimationFrequency",
        "personalTargetedSpellBorderAnimationInset",
        "personalTargetedSpellBorderAnimationLength",
        "personalTargetedSpellBorderAnimationMask",
        "personalTargetedSpellBorderAnimationOffsetX",
        "personalTargetedSpellBorderAnimationOffsetY",
        "personalTargetedSpellBorderAnimationParticles",
        "personalTargetedSpellBorderAnimationScale",
        "personalTargetedSpellBorderAnimationSidesAxis",
        "personalTargetedSpellBorderAnimationThickness",
        "personalTargetedSpellBorderAnimationType",
        "personalTargetedSpellBorderBlendMode",
        "personalTargetedSpellBorderColor",
        "personalTargetedSpellBorderGradientDirection",
        "personalTargetedSpellBorderGradientEndColor",
        "personalTargetedSpellBorderGradientStartColor",
        "personalTargetedSpellBorderInset",
        "personalTargetedSpellBorderShadowColor",
        "personalTargetedSpellBorderShadowEnabled",
        "personalTargetedSpellBorderShadowOffsetX",
        "personalTargetedSpellBorderShadowOffsetY",
        "personalTargetedSpellBorderShadowSize",
        "personalTargetedSpellBorderSize",
        "personalTargetedSpellBorderStyle",
        "personalTargetedSpellBorderTexture",
        "personalTargetedSpellDurationColor",
        "personalTargetedSpellDurationFont",
        "personalTargetedSpellDurationOutline",
        "personalTargetedSpellDurationScale",
        "personalTargetedSpellDurationX",
        "personalTargetedSpellDurationY",
        "personalTargetedSpellEnabled",
        "personalTargetedSpellGrowth",
        "personalTargetedSpellHighlightColor",
        "personalTargetedSpellHighlightImportant",
        "personalTargetedSpellHighlightInset",
        "personalTargetedSpellHighlightSize",
        "personalTargetedSpellHighlightStyle",
        "personalTargetedSpellImportantBorderAnimationColor",
        "personalTargetedSpellImportantBorderAnimationCornerLength",
        "personalTargetedSpellImportantBorderAnimationFrequency",
        "personalTargetedSpellImportantBorderAnimationInset",
        "personalTargetedSpellImportantBorderAnimationLength",
        "personalTargetedSpellImportantBorderAnimationMask",
        "personalTargetedSpellImportantBorderAnimationOffsetX",
        "personalTargetedSpellImportantBorderAnimationOffsetY",
        "personalTargetedSpellImportantBorderAnimationParticles",
        "personalTargetedSpellImportantBorderAnimationScale",
        "personalTargetedSpellImportantBorderAnimationSidesAxis",
        "personalTargetedSpellImportantBorderAnimationThickness",
        "personalTargetedSpellImportantBorderAnimationType",
        "personalTargetedSpellImportantBorderBlendMode",
        "personalTargetedSpellImportantBorderColor",
        "personalTargetedSpellImportantBorderGradientDirection",
        "personalTargetedSpellImportantBorderGradientEndColor",
        "personalTargetedSpellImportantBorderGradientStartColor",
        "personalTargetedSpellImportantBorderInset",
        "personalTargetedSpellImportantBorderShadowColor",
        "personalTargetedSpellImportantBorderShadowEnabled",
        "personalTargetedSpellImportantBorderShadowOffsetX",
        "personalTargetedSpellImportantBorderShadowOffsetY",
        "personalTargetedSpellImportantBorderShadowSize",
        "personalTargetedSpellImportantBorderSize",
        "personalTargetedSpellImportantBorderStyle",
        "personalTargetedSpellImportantBorderTexture",
        "personalTargetedSpellImportantOnly",
        "personalTargetedSpellInArena",
        "personalTargetedSpellInBattlegrounds",
        "personalTargetedSpellInDungeons",
        "personalTargetedSpellInOpenWorld",
        "personalTargetedSpellInRaids",
        "personalTargetedSpellInterruptedDuration",
        "personalTargetedSpellInterruptedShowX",
        "personalTargetedSpellInterruptedTintAlpha",
        "personalTargetedSpellInterruptedTintColor",
        "personalTargetedSpellInterruptedXColor",
        "personalTargetedSpellInterruptedXSize",
        "personalTargetedSpellMaxIcons",
        "personalTargetedSpellScale",
        "personalTargetedSpellShowBorder",
        "personalTargetedSpellShowDuration",
        "personalTargetedSpellShowInterrupted",
        "personalTargetedSpellShowSwipe",
        "personalTargetedSpellSize",
        "personalTargetedSpellSpacing",
        "personalTargetedSpellX",
        "personalTargetedSpellY",
        "targetedSpellAlpha",
        "targetedSpellAnchor",
        "targetedSpellBorderAnimationColor",
        "targetedSpellBorderAnimationCornerLength",
        "targetedSpellBorderAnimationFrequency",
        "targetedSpellBorderAnimationInset",
        "targetedSpellBorderAnimationLength",
        "targetedSpellBorderAnimationMask",
        "targetedSpellBorderAnimationOffsetX",
        "targetedSpellBorderAnimationOffsetY",
        "targetedSpellBorderAnimationParticles",
        "targetedSpellBorderAnimationScale",
        "targetedSpellBorderAnimationSidesAxis",
        "targetedSpellBorderAnimationThickness",
        "targetedSpellBorderAnimationType",
        "targetedSpellBorderBlendMode",
        "targetedSpellBorderColor",
        "targetedSpellBorderGradientDirection",
        "targetedSpellBorderGradientEndColor",
        "targetedSpellBorderGradientStartColor",
        "targetedSpellBorderInset",
        "targetedSpellBorderShadowColor",
        "targetedSpellBorderShadowEnabled",
        "targetedSpellBorderShadowOffsetX",
        "targetedSpellBorderShadowOffsetY",
        "targetedSpellBorderShadowSize",
        "targetedSpellBorderSize",
        "targetedSpellBorderStyle",
        "targetedSpellBorderTexture",
        "targetedSpellDisableMouse",
        "targetedSpellDurationColor",
        "targetedSpellDurationFont",
        "targetedSpellDurationOutline",
        "targetedSpellDurationScale",
        "targetedSpellDurationX",
        "targetedSpellDurationY",
        "targetedSpellEnabled",
        "targetedSpellFrameLevel",
        "targetedSpellGrowth",
        "targetedSpellHideSwipe",
        "targetedSpellHighlightColor",
        "targetedSpellHighlightImportant",
        "targetedSpellHighlightInset",
        "targetedSpellHighlightSize",
        "targetedSpellHighlightStyle",
        "targetedSpellImportantBorderAnimationColor",
        "targetedSpellImportantBorderAnimationCornerLength",
        "targetedSpellImportantBorderAnimationFrequency",
        "targetedSpellImportantBorderAnimationInset",
        "targetedSpellImportantBorderAnimationLength",
        "targetedSpellImportantBorderAnimationMask",
        "targetedSpellImportantBorderAnimationOffsetX",
        "targetedSpellImportantBorderAnimationOffsetY",
        "targetedSpellImportantBorderAnimationParticles",
        "targetedSpellImportantBorderAnimationScale",
        "targetedSpellImportantBorderAnimationSidesAxis",
        "targetedSpellImportantBorderAnimationThickness",
        "targetedSpellImportantBorderAnimationType",
        "targetedSpellImportantBorderBlendMode",
        "targetedSpellImportantBorderColor",
        "targetedSpellImportantBorderGradientDirection",
        "targetedSpellImportantBorderGradientEndColor",
        "targetedSpellImportantBorderGradientStartColor",
        "targetedSpellImportantBorderInset",
        "targetedSpellImportantBorderShadowColor",
        "targetedSpellImportantBorderShadowEnabled",
        "targetedSpellImportantBorderShadowOffsetX",
        "targetedSpellImportantBorderShadowOffsetY",
        "targetedSpellImportantBorderShadowSize",
        "targetedSpellImportantBorderSize",
        "targetedSpellImportantBorderStyle",
        "targetedSpellImportantBorderTexture",
        "targetedSpellImportantOnly",
        "targetedSpellInArena",
        "targetedSpellInBattlegrounds",
        "targetedSpellInDungeons",
        "targetedSpellInOpenWorld",
        "targetedSpellInRaids",
        "targetedSpellInterruptedDuration",
        "targetedSpellInterruptedShowX",
        "targetedSpellInterruptedTintAlpha",
        "targetedSpellInterruptedTintColor",
        "targetedSpellInterruptedXColor",
        "targetedSpellInterruptedXSize",
        "targetedSpellMaxIcons",
        "targetedSpellNameplateOffscreen",
        "targetedSpellScale",
        "targetedSpellShowBorder",
        "targetedSpellShowDuration",
        "targetedSpellShowInterrupted",
        "targetedSpellSize",
        "targetedSpellSortByTime",
        "targetedSpellSortNewestFirst",
        "targetedSpellSpacing",
        "targetedSpellWarnDuplicates",
        "targetedSpellX",
        "targetedSpellY",
    },
    -- Targeted List page
    targetedList = {
        "targetedListBackgroundAlpha",
        "targetedListBorderBlendMode",
        "targetedListBorderColor",
        "targetedListBorderGradientDirection",
        "targetedListBorderGradientEndColor",
        "targetedListBorderGradientStartColor",
        "targetedListBorderInset",
        "targetedListBorderShadowColor",
        "targetedListBorderShadowEnabled",
        "targetedListBorderShadowOffsetX",
        "targetedListBorderShadowOffsetY",
        "targetedListBorderShadowSize",
        "targetedListBorderSize",
        "targetedListBorderStyle",
        "targetedListBorderTexture",
        "targetedListDurationAlign",
        "targetedListDurationAnchor",
        "targetedListDurationFontSize",
        "targetedListDurationX",
        "targetedListDurationY",
        "targetedListEnabled",
        "targetedListFadeOutDuration",
        "targetedListFont",
        "targetedListFontOutline",
        "targetedListFontSize",
        "targetedListGrowth",
        "targetedListHeight",
        "targetedListHideOutOfCombat",
        "targetedListHideOwnCasts",
        "targetedListHighlightColor",
        "targetedListHighlightImportant",
        "targetedListIconPosition",
        "targetedListImportantOnly",
        "targetedListInArena",
        "targetedListInBattlegrounds",
        "targetedListInDungeons",
        "targetedListInOpenWorld",
        "targetedListInRaids",
        "targetedListInterruptTextAlign",
        "targetedListInterruptTextAnchor",
        "targetedListInterruptTextFontSize",
        "targetedListInterruptTextWidth",
        "targetedListInterruptTextX",
        "targetedListInterruptTextY",
        "targetedListInterruptedFlashDuration",
        "targetedListInterruptibleColor",
        "targetedListMaxBars",
        "targetedListSelfTargetColor",
        "targetedListSelfTargetColorEnabled",
        "targetedListShowArrowPrefix",
        "targetedListShowArrowSuffix",
        "targetedListShowBorder",
        "targetedListShowDuration",
        "targetedListShowIcon",
        "targetedListShowSpellName",
        "targetedListShowTargetName",
        "targetedListShowUntargeted",
        "targetedListSortOrder",
        "targetedListSpacing",
        "targetedListSpellNameAlign",
        "targetedListSpellNameAnchor",
        "targetedListSpellNameFontSize",
        "targetedListSpellNameWidth",
        "targetedListSpellNameX",
        "targetedListSpellNameY",
        "targetedListStylePreset",
        "targetedListTargetNameAlign",
        "targetedListTargetNameAnchor",
        "targetedListTargetNameClassColor",
        "targetedListTargetNameFontSize",
        "targetedListTargetNameWidth",
        "targetedListTargetNameX",
        "targetedListTargetNameY",
        "targetedListTexture",
        "targetedListUninterruptibleColor",
        "targetedListWidth",
        "targetedListX",
        "targetedListY",
        "targetedListZoomIcon",
    },
    -- Legacy name/status/health text & fonts
    text = {
        "fontShadowColor",
        "fontShadowOffsetX",
        "fontShadowOffsetY",
        "groupLabelColor",
        "groupLabelEnabled",
        "groupLabelFont",
        "groupLabelFontSize",
        "groupLabelFormat",
        "groupLabelOffsetX",
        "groupLabelOffsetY",
        "groupLabelOutline",
        "groupLabelPosition",
        "healthFont",
        "healthFontSize",
        "healthTextAbbreviate",
        "healthTextAnchor",
        "healthTextColor",
        "healthTextFormat",
        "healthTextHidePercent",
        "healthTextOutline",
        "healthTextUseClassColor",
        "healthTextX",
        "healthTextY",
        "nameColorClass",
        "nameFont",
        "nameFontSize",
        "nameTextAnchor",
        "nameTextColor",
        "nameTextLength",
        "nameTextOutline",
        "nameTextTruncateMode",
        "nameTextUseClassColor",
        "nameTextX",
        "nameTextY",
        "showHealthText",
        "statusTextAnchor",
        "statusTextColor",
        "statusTextEnabled",
        "statusTextFont",
        "statusTextFontSize",
        "statusTextOutline",
        "statusTextX",
        "statusTextY",
    },
    -- Text Designer (preset library travels with this category)
    textDesigner = {
        "textDesigner",
        "textDesignerPreset",
    },
    -- Status icons (role, leader, raid target, AFK, ...)
    icons = {
        "afkIconAlpha",
        "afkIconAnchor",
        "afkIconEnabled",
        "afkIconFrameLevel",
        "afkIconHideInCombat",
        "afkIconScale",
        "afkIconShowText",
        "afkIconShowTimer",
        "afkIconText",
        "afkIconTextColor",
        "afkIconTimerColor",
        "afkIconTimerFont",
        "afkIconTimerFontSize",
        "afkIconTimerOutline",
        "afkIconTimerX",
        "afkIconTimerY",
        "afkIconX",
        "afkIconY",
        "bgCarrierIconAlpha",
        "bgCarrierIconAnchor",
        "bgCarrierIconEnabled",
        "bgCarrierIconFrameLevel",
        "bgCarrierIconScale",
        "bgCarrierIconShowText",
        "bgCarrierIconText",
        "bgCarrierIconTextColor",
        "bgCarrierIconX",
        "bgCarrierIconY",
        "centerStatusIconAnchor",
        "centerStatusIconEnabled",
        "centerStatusIconFrameLevel",
        "centerStatusIconHide",
        "centerStatusIconScale",
        "centerStatusIconX",
        "centerStatusIconY",
        "combatIconAlpha",
        "combatIconAnchor",
        "combatIconEnabled",
        "combatIconFrameLevel",
        "combatIconScale",
        "combatIconX",
        "combatIconY",
        "leaderIconAlpha",
        "leaderIconAnchor",
        "leaderIconEnabled",
        "leaderIconFrameLevel",
        "leaderIconHide",
        "leaderIconHideInCombat",
        "leaderIconScale",
        "leaderIconX",
        "leaderIconY",
        "phasedIconAlpha",
        "phasedIconAnchor",
        "phasedIconEnabled",
        "phasedIconFrameLevel",
        "phasedIconHideInCombat",
        "phasedIconScale",
        "phasedIconShowLFGEye",
        "phasedIconShowText",
        "phasedIconText",
        "phasedIconTextColor",
        "phasedIconX",
        "phasedIconY",
        "raidRoleIconAlpha",
        "raidRoleIconAnchor",
        "raidRoleIconEnabled",
        "raidRoleIconFrameLevel",
        "raidRoleIconHideInCombat",
        "raidRoleIconScale",
        "raidRoleIconShowAssist",
        "raidRoleIconShowTank",
        "raidRoleIconShowText",
        "raidRoleIconTextAssist",
        "raidRoleIconTextColor",
        "raidRoleIconTextTank",
        "raidRoleIconX",
        "raidRoleIconY",
        "raidTargetIconAlpha",
        "raidTargetIconAnchor",
        "raidTargetIconEnabled",
        "raidTargetIconFrameLevel",
        "raidTargetIconHide",
        "raidTargetIconHideInCombat",
        "raidTargetIconScale",
        "raidTargetIconX",
        "raidTargetIconY",
        "readyCheckIconAlpha",
        "readyCheckIconAnchor",
        "readyCheckIconEnabled",
        "readyCheckIconFrameLevel",
        "readyCheckIconHide",
        "readyCheckIconHideInCombat",
        "readyCheckIconPersist",
        "readyCheckIconScale",
        "readyCheckIconX",
        "readyCheckIconY",
        "resurrectionIconAlpha",
        "resurrectionIconAnchor",
        "resurrectionIconEnabled",
        "resurrectionIconFrameLevel",
        "resurrectionIconScale",
        "resurrectionIconShowText",
        "resurrectionIconTextCasting",
        "resurrectionIconTextColor",
        "resurrectionIconTextPending",
        "resurrectionIconX",
        "resurrectionIconY",
        "roleIconAlpha",
        "roleIconAnchor",
        "roleIconExternalDPS",
        "roleIconExternalHealer",
        "roleIconExternalTank",
        "roleIconFrameLevel",
        "roleIconHide",
        "roleIconHideDPS",
        "roleIconHideHealer",
        "roleIconHideInCombat",
        "roleIconHideOnlyInCombat",
        "roleIconHideTank",
        "roleIconScale",
        "roleIconShowDPS",
        "roleIconShowHealer",
        "roleIconShowTank",
        "roleIconStyle",
        "roleIconX",
        "roleIconY",
        "showRoleIcon",
        "statusIconFont",
        "statusIconFontOutline",
        "statusIconFontSize",
        "summonIconAlpha",
        "summonIconAnchor",
        "summonIconEnabled",
        "summonIconFrameLevel",
        "summonIconHideInCombat",
        "summonIconScale",
        "summonIconShowText",
        "summonIconTextAccepted",
        "summonIconTextColor",
        "summonIconTextDeclined",
        "summonIconTextPending",
        "summonIconX",
        "summonIconY",
        "vehicleIconAlpha",
        "vehicleIconAnchor",
        "vehicleIconEnabled",
        "vehicleIconFrameLevel",
        "vehicleIconHideInCombat",
        "vehicleIconScale",
        "vehicleIconShowText",
        "vehicleIconText",
        "vehicleIconTextColor",
        "vehicleIconX",
        "vehicleIconY",
    },
    -- Everything else (highlights, tooltips, range, misc)
    other = {
        "aggroColorHighThreat",
        "aggroColorHighestThreat",
        "aggroColorTanking",
        "aggroHideOnTanks",
        "aggroHighlightAlpha",
        "aggroHighlightInset",
        "aggroHighlightMode",
        "aggroHighlightThickness",
        "aggroOnlyTanking",
        "aggroUseCustomColors",
        "colorPickerGlobalOverride",
        "colorPickerOverride",
        "deadBackgroundAlpha",
        "deadBackgroundColor",
        "deadFadeEnabled",
        "deadHealthBarAlpha",
        "deadHealthTextAlpha",
        "deadNameAlpha",
        "deadUseCustomBgColor",
        "fadeDeadBackground",
        "fadeDeadBackgroundColor",
        "fadeDeadFrames",
        "fadeDeadHealthBar",
        "fadeDeadIcons",
        "fadeDeadName",
        "fadeDeadPowerBar",
        "fadeDeadStatusText",
        "fadeDeadUseCustomColor",
        "frameBorderAnimationColor",
        "frameBorderAnimationCornerLength",
        "frameBorderAnimationFrequency",
        "frameBorderAnimationInset",
        "frameBorderAnimationLength",
        "frameBorderAnimationMask",
        "frameBorderAnimationOffsetX",
        "frameBorderAnimationOffsetY",
        "frameBorderAnimationParticles",
        "frameBorderAnimationScale",
        "frameBorderAnimationSidesAxis",
        "frameBorderAnimationThickness",
        "frameBorderAnimationType",
        "frameBorderBlendMode",
        "frameBorderColor",
        "frameBorderColorSource",
        "frameBorderGradientDirection",
        "frameBorderGradientEnabled",
        "frameBorderGradientEndColor",
        "frameBorderGradientStartColor",
        "frameBorderInset",
        "frameBorderOffsetX",
        "frameBorderOffsetY",
        "frameBorderShadowColor",
        "frameBorderShadowEnabled",
        "frameBorderShadowOffsetX",
        "frameBorderShadowOffsetY",
        "frameBorderShadowSize",
        "frameBorderStyle",
        "frameBorderTexture",
        "frameBorderUseClassColor",
        "frameShowBorder",
        "healthFadeAlpha",
        "healthFadeEnabled",
        "healthFadeThreshold",
        "hfCancelOnDispel",
        "hideBlizzardFrames",
        "hideBlizzardPartyFrames",
        "hideBlizzardRaidFrames",
        "hoverHighlightAlpha",
        "hoverHighlightColor",
        "hoverHighlightInset",
        "hoverHighlightMode",
        "hoverHighlightThickness",
        "masqueBorderControl",
        "oorAbsorbBarAlpha",
        "oorAuraDesignerAlpha",
        "oorAurasAlpha",
        "oorBackgroundAlpha",
        "oorBorderAlpha",
        "oorDefensiveIconAlpha",
        "oorDispelOverlayAlpha",
        "oorEnabled",
        "oorHealthBarAlpha",
        "oorHealthTextAlpha",
        "oorIconsAlpha",
        "oorMissingBuffAlpha",
        "oorMissingHealthAlpha",
        "oorNameTextAlpha",
        "oorPowerBarAlpha",
        "oorTargetedSpellAlpha",
        "oorTextAlpha",
        "petAnchor",
        "petBackgroundColor",
        "petBorderBlendMode",
        "petBorderColor",
        "petBorderGradientDirection",
        "petBorderGradientEndColor",
        "petBorderGradientStartColor",
        "petBorderInset",
        "petBorderShadowColor",
        "petBorderShadowEnabled",
        "petBorderShadowOffsetX",
        "petBorderShadowOffsetY",
        "petBorderShadowSize",
        "petBorderSize",
        "petBorderStyle",
        "petBorderTexture",
        "petEnabled",
        "petFrameHeight",
        "petFrameWidth",
        "petGroupAnchor",
        "petGroupGrowth",
        "petGroupLabel",
        "petGroupMode",
        "petGroupOffsetX",
        "petGroupOffsetY",
        "petGroupShowLabel",
        "petGroupSpacing",
        "petHealthAnchor",
        "petHealthBgColor",
        "petHealthColor",
        "petHealthColorMode",
        "petHealthFont",
        "petHealthFontOutline",
        "petHealthFontSize",
        "petHealthTextColor",
        "petHealthX",
        "petHealthY",
        "petMatchOwnerHeight",
        "petMatchOwnerWidth",
        "petNameAnchor",
        "petNameColor",
        "petNameFont",
        "petNameFontOutline",
        "petNameFontSize",
        "petNameMaxLength",
        "petNameX",
        "petNameY",
        "petOffsetX",
        "petOffsetY",
        "petPowerBarHeight",
        "petPowerColor",
        "petPowerColorMode",
        "petShowBorder",
        "petShowHealthText",
        "petShowPowerBar",
        "petTexture",
        "rangeAlpha",
        "rangeCheckEnabled",
        "rangeCheckSpellID",
        "rangeFadeAlpha",
        "rangeUpdateInterval",
        "roleBorderColorDamager",
        "roleBorderColorHealer",
        "roleBorderColorTank",
        "selectionHighlightAlpha",
        "selectionHighlightColor",
        "selectionHighlightInset",
        "selectionHighlightMode",
        "selectionHighlightThickness",
        "showBlizzardSideMenu",
        "showMinimapButton",
        "testAnimateHealth",
        "testAnimateTargetedList",
        "testBuffCount",
        "testDebuffCount",
        "testPreset",
        "testShowAbsorbs",
        "testShowAggro",
        "testShowAuraDesigner",
        "testShowAuras",
        "testShowClassPower",
        "testShowDispelGlow",
        "testShowExternalDef",
        "testShowHealPrediction",
        "testShowIcons",
        "testShowMissingBuff",
        "testShowOutOfRange",
        "testShowPersonalTargeted",
        "testShowPets",
        "testShowReducedMaxHealth",
        "testShowSelection",
        "testShowStatusIcons",
        "testShowTargetedList",
        "testShowTargetedSpell",
        "testShowTextDesigner",
        "tooltipAuraAnchor",
        "tooltipAuraDisableInCombat",
        "tooltipAuraEnabled",
        "tooltipAuraX",
        "tooltipAuraY",
        "tooltipBindingAnchor",
        "tooltipBindingAnchorPos",
        "tooltipBindingDisableInCombat",
        "tooltipBindingEnabled",
        "tooltipBindingX",
        "tooltipBindingY",
        "tooltipBuffAnchor",
        "tooltipBuffAnchorPos",
        "tooltipBuffDisableInCombat",
        "tooltipBuffEnabled",
        "tooltipBuffX",
        "tooltipBuffY",
        "tooltipDebuffAnchor",
        "tooltipDebuffAnchorPos",
        "tooltipDebuffDisableInCombat",
        "tooltipDebuffEnabled",
        "tooltipDebuffX",
        "tooltipDebuffY",
        "tooltipDefensiveAnchor",
        "tooltipDefensiveAnchorPos",
        "tooltipDefensiveDisableInCombat",
        "tooltipDefensiveEnabled",
        "tooltipDefensiveX",
        "tooltipDefensiveY",
        "tooltipFrameAnchor",
        "tooltipFrameAnchorPos",
        "tooltipFrameDisableInCombat",
        "tooltipFrameEnabled",
        "tooltipFrameX",
        "tooltipFrameY",
        "tooltipResurrectionEnabled",
    },
    -- Pinned frame sets
    pinnedFrames = {
        "pinnedFrames",
        "pinnedHideMover",
        "pinnedSnapToGrid",
    },
    -- Aura Designer config (preset library travels with this category)
    auraDesigner = {
        "auraDesigner",
        "auraDesignerPreset",
    },
    -- Auto layouts (pulls both preset libraries)
    autoLayout = {
        "raidAutoProfiles",
    },
}

-- ===========================================
-- CATEGORY DISPLAY INFO
-- ===========================================
DF.ExportCategoryInfo = {
    position = {
        name = "Position",
        description = "Where frames appear on screen",
        order = 1,
    },
    layout = {
        name = "Frame Layout",
        description = "Size, spacing, growth, sorting",
        order = 2,
    },
    bars = {
        name = "Bars",
        description = "Health, power, absorbs, heal prediction",
        order = 3,
    },
    auras = {
        name = "Auras",
        description = "Buff & debuff icons, filters, blacklist",
        order = 4,
    },
    dispel = {
        name = "Dispel",
        description = "Dispel overlay and indicators",
        order = 5,
    },
    missingBuffs = {
        name = "Missing Buffs",
        description = "Missing raid-buff indicator",
        order = 7,
    },
    defensives = {
        name = "Defensives",
        description = "Defensive bar and external defensive icon",
        order = 8,
    },
    myBuffs = {
        name = "My Buff Indicators",
        description = "Your own buffs shown on frames",
        order = 9,
    },
    targetedSpells = {
        name = "Targeted Spells",
        description = "Targeted spell alerts (incl. personal)",
        order = 10,
    },
    targetedList = {
        name = "Targeted List",
        description = "Targeted players list",
        order = 11,
    },
    text = {
        name = "Text",
        description = "Name, status, health text & fonts",
        order = 12,
    },
    textDesigner = {
        name = "Text Designer",
        description = "Text Designer config & preset library",
        order = 13,
    },
    icons = {
        name = "Status Icons",
        description = "Role, leader, raid target, AFK, etc.",
        order = 14,
    },
    other = {
        name = "Other",
        description = "Aggro, selection, range, tooltips, pets",
        order = 15,
    },
    pinnedFrames = {
        name = "Pinned Frames",
        description = "Separate frame sets for selected players",
        order = 16,
    },
    auraDesigner = {
        name = "Aura Designer",
        description = "Spec-specific aura indicators and effects",
        order = 17,
    },
    autoLayout = {
        name = "Auto Layouts",
        description = "Raid size auto-layout profiles",
        order = 18,
    },
}

-- ===========================================
-- QUICK PRESETS
-- ===========================================
DF.ExportPresets = {
    all = {
        name = "All",
        categories = {"position", "layout", "bars", "auras", "text", "icons", "other", "pinnedFrames", "auraDesigner", "autoLayout"},
    },
    appearance = {
        name = "Appearance",
        description = "Visual style without position/layout",
        categories = {"bars", "auras", "text", "icons", "other"},
    },
    layoutOnly = {
        name = "Layout",
        description = "Position and frame dimensions only",
        categories = {"position", "layout"},
    },
    none = {
        name = "None",
        categories = {},
    },
}

-- ===========================================
-- HELPER FUNCTIONS
-- ===========================================

-- Build a reverse lookup: setting key -> category
function DF:BuildCategoryLookup()
    if self._categoryLookup then return self._categoryLookup end
    
    self._categoryLookup = {}
    for category, keys in pairs(self.ExportCategories) do
        for _, key in ipairs(keys) do
            self._categoryLookup[key] = category
        end
    end
    return self._categoryLookup
end

-- Get category for a setting key
function DF:GetSettingCategory(key)
    local lookup = self:BuildCategoryLookup()
    return lookup[key]
end

-- Extract settings for specific categories from a profile
function DF:ExtractCategorySettings(profile, categories, frameType)
    local result = {}
    local categorySet = {}
    for _, cat in ipairs(categories) do
        categorySet[cat] = true
    end
    
    for category, keys in pairs(self.ExportCategories) do
        if categorySet[category] then
            for _, key in ipairs(keys) do
                if profile[key] ~= nil then
                    result[key] = profile[key]
                end
            end
        end
    end
    
    return result
end

-- Pre-4.6.1 export strings used bundled categories: "icons" also carried the
-- Targeted Spells, Defensives, Missing Buffs and Dispel families, "auras"
-- carried Boss Debuffs, and "text" carried the Text Designer. Selecting one of
-- those names on import must keep meaning what it meant when the string was
-- created, so each old name expands to the categories its keys were re-filed
-- under. The expansion only runs for PRE-SPLIT strings: a string whose stored
-- category list names any post-split category was exported with the new lists,
-- and expanding those would override a deliberately deselected sub-category
-- (the payload carries its keys). Detection: post-split strings that select a
-- parent without its carve-outs have nothing to expand anyway (their payload
-- was trimmed by the new lists), so the stored-name check is the only case
-- that needs the gate.
local LEGACY_CATEGORY_EXPANSION = {
    icons = { "targetedSpells", "defensives", "missingBuffs", "dispel" },
    text  = { "textDesigner" },
}

-- Category names that only exist post-split: any of these in a string's
-- STORED category list marks it as exported with the new lists.
local POST_SPLIT_CATEGORIES = {
    bossDebuffs = true, dispel = true, missingBuffs = true, defensives = true,
    myBuffs = true, targetedSpells = true, targetedList = true, textDesigner = true,
}

-- Merge imported settings into profile for specific categories.
-- exportedCategories = the category list STORED IN THE STRING (not the user's
-- selection) — used only to decide whether the legacy expansion applies.
function DF:MergeCategorySettings(profile, imported, categories, exportedCategories)
    local isLegacyString = true
    if exportedCategories then
        for _, cat in ipairs(exportedCategories) do
            if POST_SPLIT_CATEGORIES[cat] then
                isLegacyString = false
                break
            end
        end
    end

    local categorySet = {}
    for _, cat in ipairs(categories) do
        categorySet[cat] = true
        local expand = isLegacyString and LEGACY_CATEGORY_EXPANSION[cat]
        if expand then
            for _, sub in ipairs(expand) do categorySet[sub] = true end
        end
    end

    for category, keys in pairs(self.ExportCategories) do
        if categorySet[category] then
            for _, key in ipairs(keys) do
                if imported[key] ~= nil then
                    profile[key] = imported[key]
                end
            end
        end
    end
end

-- ============================================================
-- EXPORT COMPLETENESS AUDIT (drift guard)
-- ============================================================
-- The category lists above are hand-maintained and historically drifted
-- against Config defaults: pre-4.6.1, 188 live settings (the whole Targeted
-- List page, the buff/debuff border families, permanent movers, My Buff
-- Indicators, ...) were in no category, so selective export silently dropped
-- them. `/df exportaudit` recomputes that drift on demand: every Party/Raid
-- default key must be either assigned to a category or EXPLICITLY declared
-- local-only below. Run it whenever defaults or categories change.

-- Keys that deliberately do NOT travel in exports (machine/window state and
-- internal escape hatches, not profile content). Underscore-prefixed
-- migration flags are excluded by rule and don't need listing.
DF.ExportLocalOnly = {
    guiScale = true, guiWidth = true, guiHeight = true, -- settings-window geometry
    minimapIcon = true,                                 -- minimap button state
    useSecureHeaders = true,                            -- internal escape hatch (no GUI)

    -- Dead legacy keys: still present in Config defaults on this branch but no
    -- longer read anywhere; their defaults are deleted outright in the pending
    -- cleanup / aura-source-removal PRs. Declared local-only so the audit is
    -- clean regardless of which of those PRs has landed.
    frameBorderAlpha = true,             -- alpha rides frameBorderColor.a
    auraSourceMode = true,               -- Direct is the only aura source
    defensiveIconShowSwipe = true,
    highlightFrames = true,
    resurrectionIconHideInCombat = true,
    targetedSpellShowSwipe = true,
}

-- Keys that legitimately appear in category lists WITHOUT a Config default
-- (GUI-write-only keys where nil is meaningful — e.g. roleBorderColor* nil
-- means "fall back to class colour" — plus top-level/legacy carriers).
local EXPORT_KEYS_WITHOUT_DEFAULTS = {
    afkIconTimerFont = true, afkIconTimerOutline = true,
    auraDesignerPreset = true, textDesignerPreset = true,
    auraDesigner = true, textDesigner = true,           -- legacy inline tables
    defensiveIconBorderColorSource = true, missingBuffIconBorderColorSource = true,
    raidPlayerGroupFirst = true,
    roleBorderColorTank = true, roleBorderColorHealer = true, roleBorderColorDamager = true,
    raidAutoProfiles = true,                            -- top-level key, special-cased in Profile.lua
    -- Config.lua lists these as `= nil` (documentation only — a nil assignment
    -- creates NO table key), so at runtime they have no default: nil means
    -- "inherit absorbBarColor". Set via the Glow Color pickers.
    absorbBarOvershieldColor = true, healAbsorbBarOvershieldColor = true,
}

-- Dev tool behind /df exportaudit. Returns true when clean.
function DF:AuditExportCategories()
    local assigned = {}
    for _, keys in pairs(DF.ExportCategories) do
        for _, k in ipairs(keys) do assigned[k] = true end
    end

    local defaults = {}
    for k in pairs(DF.PartyDefaults or {}) do defaults[k] = true end
    for k in pairs(DF.RaidDefaults or {}) do defaults[k] = true end

    local missing, phantoms = {}, {}
    for k in pairs(defaults) do
        if not assigned[k] and not DF.ExportLocalOnly[k] and k:sub(1, 1) ~= "_" then
            missing[#missing + 1] = k
        end
    end
    for k in pairs(assigned) do
        if not defaults[k] and not EXPORT_KEYS_WITHOUT_DEFAULTS[k] then
            phantoms[#phantoms + 1] = k
        end
    end
    table.sort(missing)
    table.sort(phantoms)

    if #missing == 0 and #phantoms == 0 then
        print("|cff00ff00DF exportaudit:|r clean — every default key is categorised or declared local-only.")
        return true
    end
    if #missing > 0 then
        print(("|cffff4444DF exportaudit:|r %d default key(s) in NO export category (selective export will drop them):"):format(#missing))
        for _, k in ipairs(missing) do print("  missing: " .. k) end
    end
    if #phantoms > 0 then
        print(("|cffff9900DF exportaudit:|r %d category key(s) with no Config default (typo, or add to the allowlist):"):format(#phantoms))
        for _, k in ipairs(phantoms) do print("  phantom: " .. k) end
    end
    return false
end
