"""Write DandersFrames_Options/GUI/IconManifest.lua from the icon folders on disk.

The client cannot list a folder, so the icon browser (/df debug icons) reads this
generated list instead of a hand-kept one. Run it after adding, renaming or
removing a GUI icon; Tools/mover-tests/test_icon_manifest.py fails until you do.

Usage: python Tools/generate-icon-manifest.py
"""
import pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "DandersFrames_Options/GUI/IconManifest.lua"
FOLDERS = (
    ("df",  ROOT / "DandersFrames/Media/Icons"),   # Interface\AddOns\DandersFrames\Media\Icons\
    ("kit", ROOT / "DandersUI/Media/Icons"),       # <host>\Libs\DandersUI\Media\Icons\ (GUI.MEDIA)
)

def render():
    lines = [
        "-- GENERATED by Tools/generate-icon-manifest.py -- do not edit by hand.",
        "-- Every GUI icon on disk, for the icon browser (/df debug icons). The client",
        "-- cannot list a folder, so this is the list; Tools/mover-tests/test_icon_manifest.py",
        "-- fails whenever it drifts from the icon folders.",
        "local DF = DandersFrames",
        "",
        "DF.ICON_MANIFEST = {",
    ]
    for key, folder in FOLDERS:
        names = sorted(p.stem for p in folder.glob("*.png"))
        lines.append("    %s = {" % key)
        lines.extend('        "%s",' % n for n in names)
        lines.append("    },")
    lines.append("}")
    return "\r\n".join(lines) + "\r\n"

if __name__ == "__main__":
    text = render()
    OUT.write_bytes(text.encode("utf-8"))
    total = sum(len(list(f.glob("*.png"))) for _, f in FOLDERS)
    print("wrote %s (%d icons)" % (OUT.relative_to(ROOT), total))
    sys.exit(0)
